schema_version = "1.0.0"

id = "CityGenerator"
version = "2.4.0"
name = "The City Generator2.0"
tagline = "An add-on to generate cityscapes using geometry nodes"
maintainer = "Andreas dürr <cinematiccookie@gmail.com>"
type = "add-on"
blender_version_min = "4.3.0"
license = ["Royalty Free"]