name: Build Unity WebGL

on:
  push:
    branches: [ main ]
    paths:
      - 'Unity/CraftSpace/**'
      - '!Unity/CraftSpace/README.md'
  workflow_dispatch:

jobs:
  build-unity:
    runs-on: [self-hosted, unity, configured]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build Unity WebGL
        working-directory: Unity/CraftSpace
        run: |
          # Get Unity path - this depends on your setup
          UNITY_PATH="/Applications/Unity/Hub/Editor/2022.3.20f1/Unity.app/Contents/MacOS/Unity"
          
          # Execute Unity build (replace with your actual project path and build method)
          "$UNITY_PATH" -batchmode -nographics -quit -projectPath "$(pwd)" \
            -executeMethod BuildScript.BuildWebGL \
            -logFile unity_build.log
            
      - name: Check Unity log for errors
        run: |
          if grep -q "Error" Unity/CraftSpace/unity_build.log; then
            echo "Unity build failed. See log below:"
            cat Unity/CraftSpace/unity_build.log
            exit 1
          fi
          
      - name: Copy WebGL build to SvelteKit static directory
        run: |
          mkdir -p SvelteKit/BackSpace/static/Build/WebGL
          cp -R Unity/CraftSpace/Build/WebGL/* SvelteKit/BackSpace/static/Build/WebGL/
          
      - name: Commit and push Unity build
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add SvelteKit/BackSpace/static/Build/WebGL
          git commit -m "Update Unity WebGL build [skip ci]" || echo "No changes to commit"
          git push 